[project]
name = "knowledge_page"
version = "0.1.0"
description = "A knowledge base management tool."
authors = ["Your Name <your.email@example.com>"]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "langchain",
    "langchain-community",
    "langchain-text-splitters",
    "langchain-core",
    "pypdf",
    "docx2txt",
    "unstructured[md]"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
